---
- name: Read extra_vars
  hosts: localhost
  gather_facts: no
  vars:
    - input_vars: "{{ lookup('ansible.builtin.env', 'EXTRA_VARS')}}"

  tasks:

    - name: Reading target hosts from input vars and storing as localhost fact
      set_fact:
         target_hosts: "{{ input_vars['target_hosts'] }}"
         command: "{{ input_vars['command'] }}"

- name: Network Configs Backup
  hosts: "{{ hostvars['localhost']['target_hosts'] }}"
  connection: network_cli
  gather_facts: no
  vars:
    - ansible_user: "{{ lookup('ansible.builtin.file', '/etc/secret/network_username')}}"
    - ansible_password: "{{ lookup('ansible.builtin.file', '/etc/secret/network_password')}}"
    - input_vars: "{{ lookup('ansible.builtin.env', 'EXTRA_VARS')}}"

  tasks:
    - name: Set command variable
      set_fact:
        command: "{{ hostvars['localhost']['command'] }}"
        
    - name: Cisco NXOS Command
      nxos_command:
        command: "{{ command }}"
      register: command_output
      when: ansible_network_os == "nxos"


    - name: Cisco IOS Command
      ios_command:
        command: "{{ command }}"
      register: command_output
      when: ansible_network_os == "ios"

    - name: Arista EOS Command
      eos_command:
        command: "{{ command }}"
      register: command_output
      when: ansible_network_os == "eos"

    - name: Print command output into stdout
      debug:
        msg: "{{command_output.stdout}}"
